# -*- coding: utf-8 -*-
"""student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13jMyot_oHBAy4_Fe8AxzKT7ueh8mahsk
"""

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/student - Sheet1.csv")
df.info()
df.describe()
df['Marks'].hist()
df.corr()
df.boxplot(column='Marks')
df.plot.scatter(x='study_Hours',y='Marks')

