# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xyVXdCmdN7C3TagrTCbvf7wUdG5OLreB
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df=sns.load_dataset('titanic')
df.head()
print("Shape of data:",df.shape)
print("\nColumn names:\n",df.columns)
print("\nData Info:\n")
df.info()
print("\nSummary Statistics:\n")
print(df.describe(include='all'))

print(df.isnull().sum())
plt.figure(figsize=(10,5))
sns.heatmap(df.isnull(),cbar=False,cmap='viridis')
plt.title('Missing Values Heatmap')
plt.show()

print("Duplicate rows:",df.duplicated().sum())
df=df.drop_duplicates()

sns.histplot(df['age'],kde=True,color='skyblue')
plt.title('Age Distribution')
plt.show()
sns.countplot(x='sex',data=df,palette='pastel')
plt.title('Gender Distribution')
plt.show()
sns.countplot(x='class',data=df,palette='muted')
plt.title('Passenger Class Distribution')
plt.show()

sns.countplot(x='sex',hue='survived',data=df,palette='coolwarm')
plt.title('Survival by Gender')
plt.show()
sns.countplot(x='class',hue='survived',data=df,palette='coolwarm')
plt.title('Survival by Passenger Class')
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True),annot=True,cmap='YlGnBu')
plt.title('Correlation Heatmap')
plt.show()

sns.boxplot(x=df['fare'])
plt.title('Outlier Detection in Fare')
plt.show()

sns.pairplot(df[['age','fare','pclass','survived']],hue='survived')
plt.show()

pd.crosstab(df['class'],df['sex'],margins=True)
df.groupby('class')['age'].mean()
df.groupby('class')['fare'].mean()