# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATshtaIYjjHwlmpibpRnpEUqsa-xG0lz
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
df = pd.read_csv(url, sep=';')

print("Dataset Preview (First 5 Rows):")
print(df.head())
print(f"\nDataset Shape: {df.shape} rows, {df.shape[1]} columns")

print("=== BASIC DATASET INFORMATION ===")
print("\n1. Column Names and Data Types:")
print(df.info())

print("\n2. Summary Statistics (Numerical Columns):")
print(df.describe())

print("\n3. Column Names:")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

print("\n4. Target Variable 'quality' Distribution:")
print(df['quality'].value_counts().sort_index())

print("=== MISSING VALUES ANALYSIS ===")
missing_values = df.isnull().sum()
print("Missing values per column:")
print(missing_values[missing_values >0])

if missing_values.sum() == 0:
    print(" Excellent! No missing values found.")
else:
    print(f"nTotal missing values: {missing_values.sum()}")

    plt.figure(figsize=(10, 4))
    sns.heatmap(df.isnull(), yticklabels=False, cbar=False, cmap='viridis')
    plt.title('Missing Values Heatmap')
    plt.show()

print("=== DUPLICATE ROWS ANALYSIS ===")
print(f"Number of duplicate rows: {df.duplicated().sum()}")
print(f"Percentage of duplicate: {(df.duplicated().sum()/len(df)*100):.2f}%")

if df.duplicated().sum() > 0:

    df_clean = df.drop_duplicates()
    print(f"\nAfter cleaning: {df_clean.shape[0]} rows (removed {len(df)-len(df_clean)} duplicates)")
else:
    df_clean = dfprint("No duplicates found.Dataset is clean.")

print("=== UNIVARIATE ANALYSIS ===")

df_clean.hist(bins=30, figsize=(15, 10), edgecolor='black', layout=(4,3))
plt.suptitle('Distribution of All Features', fontsize=16, y=1.02)
plt.tight_layout()
plt.show()


plt.figure(figsize=(10, 5))
ax = sns.countplot(x='quality', data=df_clean, palette='viridis')
plt.title('Distribution of Wine Quality Ratings')
plt.xlabel('Quality Score')
plt.ylabel('Count')


for p in ax.patches:
    ax.annotate(f'{p.get_height()}',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom')
plt.show()

print("=== BIVARIATE ANALYSIS ===")


plt.figure(figsize=(12, 6))
sns.boxplot(x='quality', y='alcohol', data=df_clean, palette= 'Set2')
plt.title('Alcohol Content by Wine Quality Rating')
plt.xlabel('Quality Score')
plt.ylabel('Alcohol Content (%)')
plt.show()

plt.figure(figsize=(10, 6))
scatter = plt.scatter(df_clean['fixed acidity'], df_clean['citric acid'],
                     c=df_clean['quality'], cmap='viridis', alpha=0.7)
plt.colorbar(scatter, label='Quality Rating')
plt.title('Citric Acid vs Fixed Acidity (Colored by Quality)')
plt.xlabel('Fixed Acidity')
plt.ylabel('Citric Acid')
plt.show()

print("=== CORRELATION ANALYSIS ===")


correlation_matrix = df_clean.corr()

plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, square=True, linewidths=1, cbar_kws={"shrink": 0.8})
plt.title('Correlation Heatmap of Wine Features', fontsize=16)
plt.tight_layout()
plt.show()

print("\nTop correlations 'quality':")
quality_corr = correlation_matrix['quality'].sort_values(ascending=False)
for i, (feature, corr) in enumerate(quality_corr.items(), 1):
    print(f"{i:2}. {feature:20}: {corr:.3f}")

print("=== PAIWISE RELATIONSHIPS ===")


selected_features = ['alcohol', 'volatile acidity', 'citric acid', 'residual sugar', 'quality']


pair_grid = sns.pairplot(df_clean[selected_features], hue='quality',
                         palette='viridis', diag_kind='kde', height=2.5)
pair_grid.fig.suptitle('Pairwise Relationships of Selected Features', y=1.02)
plt.show()


pd.plotting.scatter_matrix(df_clean[selected_features], figsize=(12, 10), alpha=0.6)
plt.suptitle('Scatter Matrix of Selected Features', fontsize=16, y=1.02)
plt.show()

print("=== CATEGORICAL INSIGHTS ===")


df_clean['quality_category'] = pd.cut(df_clean['quality'],
                                      bins=[0,4,6, 10],
                                      labels=['Law', 'Medium', 'High'])

print("\n1. Wine Quality Categories:")
quality_dist = df_clean['quality_category'].value_counts()
print(quality_dist)


plt.figure(figsize=(10, 5))
colors = ['#FF6B6B', '#4ECDC4', '#45B7D1']
quality_dist.plot(kind='pie', autopct='%1.1f%%', colors=colors, startangle=90)
plt.title('Distribution of Wine Quality Categories')
plt.ylabel('')
plt.show()

print("\n2.Feature Statistics by Quality Category:")
for feature in ['alcohol', 'volatile acidity', 'sulphates']:
    print(f"\n--- {feature.upper()} ---")
    stats = df_clean.groupby('quality_category')[feature].agg(['mean', 'std', 'min', 'max'])
    print(stats.round(3))